name: 'vvrjs/publish-then-tag@v0.1'
description: 'action to publish npm package and set the same git tag to git commit'
inputs:
  npmToken:
    description: 'npm authorization token, will be appended to .npmrc as is'
    required: true
  githubToken:
    description: 'github authorization token, will be used to create a tag via github api'
    required: true
  repo:
    description: '$GITHUB_REPOSITORY'
    required: true
  sha:
    description: '$GITHUB_SHA'
    required: true
  mode:
    description: 'operation mode CI or CD'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
